executable              = condorbatchscript_UL_test.sh
arguments               = $(Item)

output                  = TaggerOutput_20230104_UL_test/Out_$(Item).out
error                   = TaggerOutput_20230104_UL_test/Out_$(Item).err
log                     = TaggerOutput_20230104_UL_test/Out_$(Item).log

request_memory          = 4000M
+JobFlavour             = "nextweek"

#https://www-auth.cs.wisc.edu/lists/htcondor-users/2010-September/msg00009.shtml
periodic_remove         = JobStatus == 5
WhenToTransferOutput    = ON_EXIT_OR_EVICT

queue from seq 1 110 |

