executable              = condorbatchscript_MC_validation.sh
arguments               = $(i)

output                  = TaggerOutput_20220610_MC_validation/Out_$(i).out
error                   = TaggerOutput_20220610_MC_validation/Out_$(i).err
log                     = TaggerOutput_20220610_MC_validation/Out_$(i).log

request_memory          = 4000M
+JobFlavour             = "nextweek"

#https://www-auth.cs.wisc.edu/lists/htcondor-users/2010-September/msg00009.shtml
periodic_remove         = JobStatus == 5
WhenToTransferOutput    = ON_EXIT_OR_EVICT

queue i in 134 135 136 137
